"""
====================================================
Enterprise AI Email Automation
HTML Email Formatter
====================================================
"""


def generate_html_email(subject, body):

    html = f"""
<!DOCTYPE html>

<html>

<head>

<meta charset="UTF-8">

<style>

body{{
    background:#f4f7fb;
    font-family:Arial,Helvetica,sans-serif;
    margin:0;
    padding:30px;
}}

.container{{
    max-width:700px;
    margin:auto;
    background:white;
    border-radius:12px;
    overflow:hidden;
    box-shadow:0 2px 10px rgba(0,0,0,.08);
}}

.header{{
    background:#2563eb;
    color:white;
    padding:25px;
    font-size:24px;
    font-weight:bold;
    text-align:center;
}}

.content{{
    padding:35px;
    color:#333;
    line-height:1.8;
    font-size:16px;
}}

.footer{{
    background:#f1f5f9;
    padding:20px;
    text-align:center;
    color:#666;
    font-size:13px;
}}

.signature{{
    margin-top:30px;
}}

.subject{{
    color:#2563eb;
    font-size:18px;
    font-weight:bold;
    margin-bottom:20px;
}}

</style>

</head>

<body>

<div class="container">

<div class="header">

📧 Enterprise AI Email Automation

</div>

<div class="content">

<div class="subject">

Subject: {subject}

</div>

{body.replace(chr(10), "<br><br>")}

<div class="signature">

<br>

Regards,

<br>

<b>Customer Support Team</b>

<br>

Enterprise AI

</div>

</div>

<div class="footer">

This email was generated by Enterprise AI Email Automation.

<br>

contact.sugumarai@gmail.com

</div>

</div>

</body>

</html>

"""

    return html


# =====================================================
# Plain Text → HTML
# =====================================================

def format_email(state):

    subject = state.get("subject", "Customer Support")

    body = state.get("final_email", "")

    html = generate_html_email(subject, body)

    state["html_email"] = html

    return state
